artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion
  workspace: "el-abbas-aymane"
  project: "chest-x-ray-chee0-31zb6"
  version: 1 # Update with your exported version number
